N = int(input("Digite um numero para saber a sua TABUADA: "))

print(20*"=")
print("{} x  1 = {:<3}".format(N, (N*1)))
print("{} x  2 = {:<3}".format(N, (N*2)))
print("{} x  3 = {:<3}".format(N, (N*3)))
print("{} x  4 = {:<3}".format(N, (N*4)))
print("{} x  5 = {:<3}".format(N, (N*5)))
print("{} x  6 = {:<3}".format(N, (N*6)))
print("{} x  7 = {:<3}".format(N, (N*7)))
print("{} x  8 = {:<3}".format(N, (N*8)))
print("{} x  9 = {:<3}".format(N, (N*9)))
print("{} x 10 = {:<3}".format(N, (N*10)))
print(20*"=")

